# -*- coding: utf-8 -*-
"""Excercises_sec3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxltddDowwqVwkqdPfxwgjJrX6TPhVln

# 1.Create a tensor a from `list(range(9))`. Predict and then check the size, offset, and stride :
"""

import torch

a = torch.tensor(list(range(9)))
print("Tensor a:", a)
print("Size:", a.size())
print("Offset:", a.storage_offset())
print("Stride:", a.stride())

"""## a.Create a new tensor using `b = a.view(3, 3)`. What does view do? Check that a and b share the same storage."""

b = a.view(3, 3)
print("Tensor b:\n", b)
print("b size:", b.size())
print("b offset:", b.storage_offset())
print("b stride:", b.stride())
print("Same storage?", a.storage().data_ptr() == b.storage().data_ptr())

"""##b.Create a tensor `c = b[1:,1:]`. Predict and then check the size, offset, and stride."""

c = b[1:,1:]
print("Tensor c:\n", c)
print("c size:", c.size())
print("c offset:", c.storage_offset())
print("c stride:", c.stride())

"""#2.Pick a mathematical operation like cosine or square root. Can you find a corresponding function in the torch library?

##a.Apply the function element-wise to a. Why does it return an error?
"""

result = torch.cos(a)

"""##b.What operation is required to make the function work?"""

result = torch.cos(a.float())
print("Cosine of a:", result)

"""##c.Is there a version of your function that operates in place?"""

a_float = a.float()
print("Before cos_:", a_float)
a_float.cos_()
print("After cos_:", a_float)